--- Grocery Store Management --

Create database IF NOT EXISTS GroceryStoreDB;
Use GroceryStoreDB;

-- 1. Supplier Table
CREATE TABLE IF NOT EXISTS supplier (
    sup_id TINYINT PRIMARY KEY,
    sup_name VARCHAR(255),
    address TEXT
);

-- 2. Categories Table
CREATE TABLE IF NOT EXISTS categories (
    cat_id TINYINT PRIMARY KEY,
    cat_name VARCHAR(255)
);

-- 3. Employees Table
CREATE TABLE IF NOT EXISTS employees (
    emp_id TINYINT PRIMARY KEY,
    emp_name VARCHAR(255),
    hire_date VARCHAR(255)
);

-- 4. Customers Table
CREATE TABLE IF NOT EXISTS customers (
    cust_id SMALLINT PRIMARY KEY,
    cust_name VARCHAR(255),
    address TEXT
);

-- 5. Products Table
CREATE TABLE IF NOT EXISTS products (
    prod_id TINYINT PRIMARY KEY,
    prod_name VARCHAR(255),
    sup_id TINYINT,
    cat_id TINYINT,
    price DECIMAL(10,2),
    FOREIGN KEY (sup_id) REFERENCES supplier(sup_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (cat_id) REFERENCES categories(cat_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- 6. Orders Table
CREATE TABLE IF NOT EXISTS orders (
    ord_id SMALLINT PRIMARY KEY,
    cust_id SMALLINT,
    emp_id TINYINT,
    order_date VARCHAR(255),
    FOREIGN KEY (cust_id) REFERENCES customers(cust_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);


-- 7. Order_Details Table
CREATE TABLE IF NOT EXISTS order_details (
    ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ord_id SMALLINT,
    prod_id TINYINT,
    quantity TINYINT,
    each_price DECIMAL(10,2),
    total_price DECIMAL(10,2),
    FOREIGN KEY (ord_id) REFERENCES orders(ord_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (prod_id) REFERENCES products(prod_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- Customer Insights --
-- 1. How many unique customers have placed orders?
Select Count(Distinct cust_id) As Unique_customers from orders;

-- 2. Which customers have placed the highest number of orders?
SELECT c.cust_id, c.cust_name, COUNT(o.ord_id) AS total_orders
FROM customers c
JOIN orders o ON c.cust_id = o.cust_id
GROUP BY c.cust_id, c.cust_name
ORDER BY total_orders DESC;

-- 3. What is the total and average purchase value per customer?
SELECT 
    c.cust_id,
    c.cust_name,
    SUM(od.total_price) AS total_purchase_value,
    AVG(od.total_price) AS avg_purchase_value
FROM customers c
JOIN orders o ON c.cust_id = o.cust_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY c.cust_id, c.cust_name;

-- 4. Who are the top 5 customers by total purchase amount?
SELECT 
      c.cust_id,
	  c.cust_name,
      SUM(od.total_price) as total_purchase_value
FROM customers c
JOIN orders o ON c.cust_id = o.cust_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY c.cust_id,c.cust_name
ORDER BY total_purchase_value DESC LIMIT 5;

-- Product Performance --
-- 1. How many products exist in each category?
SELECT
     ca.cat_id,
     ca.cat_name,
     COUNT(p.prod_id) as product_count
from categories ca
JOIN products p ON ca.cat_id = p.cat_id
GROUP BY ca.cat_id,ca.cat_name
ORDER BY product_count DESC;

-- 2. What is the average price of products by category?
SELECT
     ca.cat_id,
     ca.cat_name,
     ROUND(AVG(p.price),2) as avg_product_price 
from categories ca
LEFT JOIN products p ON ca.cat_id = p.cat_id
GROUP BY ca.cat_id,ca.cat_name
ORDER BY avg_product_price DESC;

-- 3.Which products have the highest total sales volume (by quantity)?
SELECT
  p.prod_id,
  p.prod_name,
  COALESCE(SUM(od.quantity), 0) AS total_quantity_sold
FROM products p
LEFT JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_id, p.prod_name
ORDER BY total_quantity_sold DESC;

-- 4. What is the total revenue generated by each product?
SELECT
  p.prod_id,
  p.prod_name,
  COALESCE(SUM(od.total_price), 0.00) AS total_revenue
FROM products p
LEFT JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_id, p.prod_name
ORDER BY total_revenue DESC;

-- 5. How do product sales vary by category and supplier?
SELECT
  ca.cat_id, ca.cat_name,
  s.sup_id, s.sup_name,
  COALESCE(SUM(od.quantity), 0)        AS total_units_sold,
  COALESCE(SUM(od.total_price), 0.00)  AS total_revenue,
  COUNT(DISTINCT p.prod_id)            AS num_products_in_group
FROM categories ca
JOIN products p ON p.cat_id = ca.cat_id
JOIN supplier s ON p.sup_id = s.sup_id
LEFT JOIN order_details od ON od.prod_id = p.prod_id
GROUP BY ca.cat_id, ca.cat_name, s.sup_id, s.sup_name
ORDER BY ca.cat_name, total_revenue DESC;

-- Sales and Trends --
-- 1. How many orders have been placed in total?
SELECT COUNT(*) AS total_orders
FROM orders;

-- 2. What is the average value per order?
SELECT 
    AVG(order_total) AS avg_order_value
FROM (
    SELECT 
        o.ord_id,
        SUM(od.total_price) AS order_total
    FROM orders o
    JOIN order_details od ON o.ord_id = od.ord_id
    GROUP BY o.ord_id
) AS sub;

-- 3. On which dates were the most orders placed?
SELECT 
    order_date,
    COUNT(*) AS total_orders
FROM orders
GROUP BY order_date
ORDER BY total_orders DESC;

-- 4. What are the monthly trends in order volume and revenue?
SELECT  
    DATE_FORMAT(STR_TO_DATE(o.order_date, '%d/%m/%Y'), '%Y-%m') AS month,
    COUNT(DISTINCT o.ord_id) AS total_orders,
    SUM(od.total_price) AS total_revenue
FROM orders o
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY month
ORDER BY month;


-- 5.How do order patterns vary across weekdays and weekends?
SELECT
    CASE 
        WHEN DAYOFWEEK(order_date) IN (1,7) THEN 'Weekend'
        ELSE 'Weekday'
    END AS day_type,
    COUNT(*) AS total_orders
FROM orders
GROUP BY day_type;

-- Supplier Contribution --
-- 1. How many suppliers are there in the database?
Select Count(Distinct sup_id) as Supplier_count from supplier;

-- 2. Which supplier provides the most products?
SELECT 
    s.sup_id,
    s.sup_name,
    COUNT(p.prod_id) AS total_products
FROM supplier s
JOIN products p ON s.sup_id = p.sup_id
GROUP BY s.sup_id, s.sup_name
ORDER BY total_products DESC;

-- 3.What is the average price of products from each supplier?
SELECT 
    s.sup_id,
    s.sup_name,
    ROUND(AVG(p.price), 2) AS avg_price
FROM supplier s
JOIN products p ON s.sup_id = p.sup_id
GROUP BY s.sup_id, s.sup_name
ORDER BY avg_price DESC;

-- 4.Which suppliers contribute the most to total product sales (by revenue)?
SELECT
    s.sup_id,
    s.sup_name,
    COALESCE(SUM(od.total_price), 0) AS total_revenue
FROM supplier s
JOIN products p ON s.sup_id = p.sup_id
LEFT JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY s.sup_id, s.sup_name
ORDER BY total_revenue DESC;

-- Employee Performance --
-- 1. How many employees have processed orders?
SELECT COUNT(DISTINCT o.emp_id) AS employees_with_orders
FROM orders o
JOIN employees e ON o.emp_id = e.emp_id
WHERE o.emp_id IS NOT NULL;

-- 2. Which employees have handled the most orders?
SELECT
  e.emp_id,
  e.emp_name,
  COUNT(o.ord_id) AS orders_handled
FROM employees e
LEFT JOIN orders o ON e.emp_id = o.emp_id
GROUP BY e.emp_id, e.emp_name
ORDER BY orders_handled DESC;

-- 3,What is the total sales value processed by each employee?
SELECT
  e.emp_id,
  e.emp_name,
  COALESCE(SUM(od.total_price), 0.00) AS total_sales_value
FROM employees e
LEFT JOIN orders o       ON e.emp_id = o.emp_id
LEFT JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY e.emp_id, e.emp_name
ORDER BY total_sales_value DESC;

-- 4.What is the average order value handled per employee?
SELECT
  e.emp_id,
  e.emp_name,
  ROUND(COALESCE(AVG(sub.order_total), 0), 2) AS avg_order_value,
  COUNT(sub.ord_id) AS orders_handled
FROM employees e
LEFT JOIN (
  SELECT
    o.ord_id,
    o.emp_id,
    SUM(od.total_price) AS order_total
  FROM orders o
  JOIN order_details od ON o.ord_id = od.ord_id
  GROUP BY o.ord_id, o.emp_id
) AS sub ON e.emp_id = sub.emp_id
GROUP BY e.emp_id, e.emp_name
ORDER BY avg_order_value DESC;

-- Order Details Deep Dive --
-- 1. What is the relationship between quantity ordered and total price?
SELECT
  COUNT(*)                                       AS n,
  ROUND((COUNT(*)*SUM(quantity * total_price) - SUM(quantity)*SUM(total_price))
        / NULLIF(SQRT((COUNT(*)*SUM(POW(quantity,2)) - POW(SUM(quantity),2))
                      *(COUNT(*)*SUM(POW(total_price,2)) - POW(SUM(total_price),2))),0), 6)
                                                  AS pearson_correlation
FROM order_details;

-- 2. What is the average quantity ordered per product?
SELECT
  p.prod_id,
  p.prod_name,
  ROUND(COALESCE(AVG(od.quantity), 0), 2)    AS avg_quantity_per_order,
  COALESCE(SUM(od.quantity), 0)              AS total_quantity_sold,
  COALESCE(COUNT(DISTINCT od.ord_id), 0)     AS orders_with_product
FROM products p
LEFT JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_id, p.prod_name
ORDER BY avg_quantity_per_order DESC;

-- 3. How does the unit price vary across products and orders?
-- 3a) Summary Statistics per product
SELECT
  p.prod_id,
  p.prod_name,
  ROUND(AVG(od.each_price), 2)          AS avg_unit_price,
  ROUND(MIN(od.each_price), 2)          AS min_unit_price,
  ROUND(MAX(od.each_price), 2)          AS max_unit_price,
  COUNT(od.ord_detID)                   AS observations
FROM products p
LEFT JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_id, p.prod_name;



























